# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28ed6f5fc478c264ead468515b89e671e26aa1b537c59f148a94ece07a55f1ece2d4fbb6deffe0cad0e51247a12c752cbd74c728f3061b02fc7bbb6ea6645814

test:
  secret_key_base: 0a5e150554636355b959f754f4d0028da0c79fb8edd74a0bcf8f9110e6739479f91915aef78b959c49a0b6b930d194411b52a2ffdbc5632ba80d3bfcda571e8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
